"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { AppProvider } from "./context/AppContext";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dever Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isSignInPage = pathname === "/auth/sign-in";
  const isSignUpPage = pathname === "/auth/sign-up";
  const isForgotPassPage = pathname === "/auth/forgot-password";
  const isRestPassPage = pathname === "/auth/reset-password";
  return (
    <html lang="en"  suppressHydrationWarning={true}>
      <body className={inter.className}  suppressHydrationWarning={true}>
        <AppProvider>
          {!isSignInPage &&
            !isSignUpPage &&
            !isForgotPassPage &&
            !isRestPassPage && <Header />}
          {!isSignInPage &&
            !isSignUpPage &&
            !isForgotPassPage &&
            !isRestPassPage && <Sidebar />}
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
