"use client";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { AppProvider } from "./context/AppContext";
import { usePathname } from "next/navigation";
import ToastNotificationComp from "@/components/ToastNotificationComp";
const inter = Inter({ subsets: ["latin"] });
import { Provider } from "react-redux";
import { store } from "../redux/store";

// export const metadata: Metadata = {
//   title: "Dever Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const specialPaths = [
    "/auth/sign-in",
    "/auth/sign-up",
    "/auth/forgot-password",
    "/auth/reset-password",
  ];
  const pathname = usePathname();
  const isSpecial = specialPaths.includes(pathname);
  
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider store={store}>
          <AppProvider>
            {!isSpecial && <Header />}
            {!isSpecial && <Sidebar />}
            {children}
          </AppProvider>
          <ToastNotificationComp />
        </Provider>
      </body>
    </html>
  );
}
